name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: [5.1, 5.2]
        arch: [win64, win32]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone wine
      run: git clone https://github.com/wine-mirror/wine --depth 1 -b wine-${{ matrix.version }}
    - name: install build-essential
      run: sudo apt-get install build-essential flex bison
    - name: apply patch
      run: |
        cd wine
        git apply $(pwd)/../headless.patch
    - name: configure
      run: |
        cd wine
        ./configure \
          --without-alsa \
          --without-capi \
          --without-cms \
          --without-coreaudio \
          --without-cups \
          --without-curses \
          --without-dbus \
          --without-faudio \
          --without-gettext \
          --without-gphoto \
          --without-glu \
          --without-gnutls \
          --without-gsm \
          --without-gssapi \
          --without-gstreamer \
          --without-hal \
          --without-inotify \
          --without-jpeg \
          --without-krb5 \
          --without-ldap \
          --without-mingw \
          --without-mpg123 \
          --without-netapi \
          --without-openal \
          --without-opencl \
          --without-opengl \
          --without-osmesa \
          --without-oss \
          --without-pcap \
          --without-pulse \
          --without-sane \
          --without-sdl \
          --without-tiff \
          --without-udev \
          --without-unwind \
          --without-v4l2 \
          --without-vkd3d \
          --without-vulkan \
          --without-xcomposite \
          --without-xcursor \
          --without-xfixes \
          --without-xinerama \
          --without-xinput \
          --without-xinput2 \
          --without-xml \
          --without-xrandr \
          --without-xrender \
          --without-xshape \
          --without-xshm \
          --without-xslt \
          --disable-tests \
          --disable-vcruntime140_1 \
          --enable-${{ matrix.arch }} \
          --prefix=$(pwd)/../dist
    - name: build
      run: |
        cd wine
        make -j4
    - name: install
      run: |
        mkdir dist
        pushd wine
        make install
        popd
        tar cvfJ wine.tar.xz dist/*
    - name: Upload artifact ${{ matrix.version }}-${{ matrix.arch }}
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.version }}-${{ matrix.arch }}
        path: dist
    - name: Create a new GitHub release if a new tag is pushed
      uses: svenstaro/upload-release-action@v1-release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: wine.tar.xz
        asset_name: wine-${{ matrix.version }}-${{ matrix.arch }}.tar.xz
        tag: ${{ github.ref }}
        overwrite: true
